import './globals.css'
import { Inter } from 'next/font/google'
import Layout from '@/components/layout'
import LoginModal from '@/components/modals/LoginModal'
import RegisterModal from '@/components/modals/RegisterModal'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children
}: {
  children: React.ReactNode,
  
})
{
  return (
    
    <html lang="en">
      <body className={inter.className}>
        <>


        {/* <RegisterModal/>
        <LoginModal/>
        <Layout>
{children}
        </Layout> */}
        </>
        </body>
    </html>
  )
}


